### caller workflow: azure-static-web-apps-gentle-ocean-066456300.yml ###
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  call_aswa_flow:
    uses: jintfs/my-second-static-web-app/.github/workflows/build-test-2.yaml@main

    with:
      event_name: ${{ github.event_name }}
      event_action: ${{ github.event.action }}
      app_location: "/"
      api_location: "api"
      output_location: "dist/angular-basic"

    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      aswa_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_OCEAN_066456300 }}
